-- Migration number: 0001 	 2024-12-27T22:04:18.794Z
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS waitlist;
CREATE TABLE IF NOT EXISTS waitlist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
